//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employes()
        {
            this.Missions = new HashSet<Missions>();
        }
    
        public string Login { get; set; }
        public bool Intervenant { get; set; }
        public string Mail { get; set; }
        public string Secteur { get; set; }
        public string Nom { get; set; }
        public byte[] Photo { get; set; }
        public string Reporting { get; set; }
    
        public virtual Secteurs Secteurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Missions> Missions { get; set; }
    }
}
