//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int ID { get; set; }
        public string SenderName { get; set; }
        public string SenderMail { get; set; }
        public string MailObject { get; set; }
        public string MailText { get; set; }
    }
}
