//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missions
    {
        public int ID { get; set; }
        public string Nom_Mission { get; set; }
        public string Nom_Secteur { get; set; }
        public string Date_passage { get; set; }
        public bool Passage { get; set; }
        public int ID_Parcours { get; set; }
        public string Remarque { get; set; }
        public bool Planifié { get; set; }
        public Nullable<int> ID_Formateur { get; set; }
        public bool Applicable { get; set; }
    
        public virtual Utilisateurs Utilisateurs { get; set; }
        public virtual Parcours Parcours { get; set; }
    }
}
