//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missions
    {
        public int ID { get; set; }
        public string Nom_Mission { get; set; }
        public string Nom_Secteur { get; set; }
        public string Login_Interlocuteur { get; set; }
        public string Date_passage { get; set; }
        public bool Passage { get; set; }
        public int ID_Parcours { get; set; }
        public string Remarque { get; set; }
    
        public virtual Employes Employes { get; set; }
        public virtual Parcours Parcours { get; set; }
    }
}
