//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeleContrat
    {
        public int ID { get; set; }
        public int ID_Modele { get; set; }
        public int ID_Contrat { get; set; }
    
        public virtual Contrat Contrat { get; set; }
        public virtual Modele Modele { get; set; }
    }
}
