//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modele()
        {
            this.ModeleContrat = new HashSet<ModeleContrat>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public bool CDI { get; set; }
        public bool CDD { get; set; }
        public bool Stage { get; set; }
        public bool Mutation { get; set; }
        public bool Intérimaire { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModeleContrat> ModeleContrat { get; set; }
    }
}
