//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Parcours_IntegrationEntities : DbContext
    {
        public Parcours_IntegrationEntities()
            : base("name=Parcours_IntegrationEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Employes> Employes { get; set; }
        public virtual DbSet<Missions> Missions { get; set; }
        public virtual DbSet<Modele> Modele { get; set; }
        public virtual DbSet<ModeleContrat> ModeleContrat { get; set; }
        public virtual DbSet<Parcours> Parcours { get; set; }
        public virtual DbSet<Secteurs> Secteurs { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
    }
}
