//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parcours()
        {
            this.Comment = new HashSet<Comment>();
            this.Missions = new HashSet<Missions>();
            this.Signatures = new HashSet<Signatures>();
            this.Purge = new HashSet<Purge>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string Date_entrée { get; set; }
        public Nullable<int> Type_Contrat { get; set; }
        public bool Complété { get; set; }
        public string Poste { get; set; }
        public Nullable<System.DateTime> Entrée { get; set; }
        public Nullable<int> EquipeID { get; set; }
        public Nullable<int> ID_Resp { get; set; }
        public Nullable<int> ID_Employé { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Contrat Contrat { get; set; }
        public virtual Equipe Equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Missions> Missions { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
        public virtual Utilisateurs CompteInformatique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signatures> Signatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purge> Purge { get; set; }
    }
}
