//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParcoursIntegrationEntities : DbContext
    {
        public ParcoursIntegrationEntities()
            : base("name=ParcoursIntegrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Equipe> Equipe { get; set; }
        public virtual DbSet<Missions> Missions { get; set; }
        public virtual DbSet<ModeleContrat> ModeleContrat { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
        public virtual DbSet<Utilisateurs_Services> Utilisateurs_Services { get; set; }
        public virtual DbSet<Parcours> Parcours { get; set; }
        public virtual DbSet<Modele> Modele { get; set; }
        public virtual DbSet<Purge> Purge { get; set; }
        public virtual DbSet<Signatures> Signatures { get; set; }
    }
}
