//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParcoursIntegrationEntities : DbContext
    {
        public ParcoursIntegrationEntities()
            : base("name=ParcoursIntegrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Equipe> Equipe { get; set; }
        public virtual DbSet<Missions> Missions { get; set; }
        public virtual DbSet<ModeleContrat> ModeleContrat { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
        public virtual DbSet<Utilisateurs_Services> Utilisateurs_Services { get; set; }
        public virtual DbSet<Parcours> Parcours { get; set; }
        public virtual DbSet<Modele> Modele { get; set; }
    }
}
