//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parcours()
        {
            this.Comment = new HashSet<Comment>();
            this.Missions = new HashSet<Missions>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string Date_entrée { get; set; }
        public Nullable<int> Type_Contrat { get; set; }
        public bool Complété { get; set; }
        public string Poste { get; set; }
        public Nullable<System.DateTime> Entrée { get; set; }
        public Nullable<int> EquipeID { get; set; }
        public Nullable<int> ID_Resp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Contrat Contrat { get; set; }
        public virtual Equipe Equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Missions> Missions { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
