//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcours_integration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateurs()
        {
            this.Missions = new HashSet<Missions>();
            this.Utilisateurs_Services = new HashSet<Utilisateurs_Services>();
            this.ParcoursResponsable = new HashSet<Parcours>();
            this.ParcoursEmployé = new HashSet<Parcours>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Login { get; set; }
        public string UserMail { get; set; }
        public string UserPhone { get; set; }
        public bool EstResponsable { get; set; }
        public bool EstFormateur { get; set; }
        public byte[] Photo { get; set; }
        public bool EstAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Missions> Missions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilisateurs_Services> Utilisateurs_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcours> ParcoursResponsable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcours> ParcoursEmployé { get; set; }
    }
}
